---

docker:
  version: 17.06.0-ce
  repo_url: "https://download.docker.com/linux/fedora/docker-ce.repo"
  start: true
  service_enabled: yes

docker_compose:
    install: true
    version: "1.14.0"
    path: /usr/local/bin/docker-compose
