---
__common_packages:
  - autoconf
  - bash-completion
  - build-essential
  - bzip2
  - colortest
  - curl
  - diffutils
  - dnf
  - dos2unix
  - gawk
  - gcc
  - git
  - grep
  - gzip
  - htop
  - httping
  - iftop
  - iotop
  - jq
  - less
  - make
  - nano
  - nmap
  - ntop
  - ntp
  - ntpdate
  - openssl
  - p7zip
  - pbzip2
  - pwgen
  - software-properties-common
  - tar
  - terminator
  - unzip
  - vim
  - wget
  - whois
  - zip
  - unzip
