---

- name: Create {{ parent_dir }} directory
  file:
    path: "{{ parent_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: yes

- stat:
    path: "{{idea.dir}}"
  register: idea_dir


- block:

  - debug:
      msg: "download url : {{idea.url}}"

  - name: get Idea Intellij tarball
    get_url:
      url: "{{idea.url}}"
      dest: "/tmp/{{idea.file}}"

  - name: Create /tmp/ideaIC-{{idea.version}} directory
    file:
      path: "/tmp/ideaIC-{{idea.version}}"
      state: directory

  - name: Unarchive Intellij
    unarchive:
      extra_opts: ['--strip-components=1', '--show-stored-names']
      src: "/tmp/{{idea.file}}"
      dest: "/tmp/ideaIC-{{idea.version}}"
      copy: no

  - name: Create {{idea.dir}} directory
    command: "mv /tmp/ideaIC-{{idea.version}} {{idea.dir}}"

  - name: Remove old symlink
    file:
      path: "{{parent_dir}}/idea"
      state: absent

  - file:
      src: "{{idea.dir }}"
      dest: "{{parent_dir}}/idea"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: link

  when: idea_dir.stat.isdir is not defined

- name: Remove old path configuration
  file:
    path: /etc/profile.d/idea.sh
    state: absent
  become: yes

- name: "Configuring Idea Intellij {{idea.dir}} and add $PATH."
  template:
    src: idea.sh.j2
    dest: /etc/profile.d/idea.sh
    mode: 0644
  become: yes

- name: "Add Intellij to system applications"
  template:
    src: idea.desktop.j2
    dest: /usr/share/applications/idea.desktop
    mode: 0644
  become: yes
