---

- name: Define apps_dir
  set_fact:
    apps_dir: "{{ apps_dir }}"
  when: apps_dir is undefined

- stat:
    path: "{{apps_dir}}/{{ idea.exploded_dir }}"
  register: idea_dir

- name: Create {{ apps_dir }} directory
  file:
    path: "{{ apps_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: yes

- block:

  - debug:
      msg: "download url : {{idea.url}}"

  - name: get Idea Intellij tarball
    get_url:
      url: "{{idea.url}}"
      dest: "/tmp/ideaIC-{{ idea.version}}}-no-jdk.tar.gz"

  - name: Unarchive Intellij
    unarchive:
      src: "/tmp/ideaIC-{{ idea.version}}}-no-jdk.tar.gz"
      dest: "{{apps_dir}}"
      copy: no

  when: idea_dir.stat.isdir is not defined


- name: Remove old symlink
  file:
    path: "{{apps_dir}}/idea"
    state: absent

- file:
    src: "{{apps_dir}}/{{ idea.exploded_dir }}"
    dest: "{{apps_dir}}/idea"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: Remove old path configuration
  file:
    path: /etc/profile.d/idea.sh
    state: absent
  become: yes

- name: "Configuring Idea Intellij {{apps_dir}}/{{idea.exploded_dir}} and add $PATH."
  template:
    src: idea.sh.j2
    dest: /etc/profile.d/idea.sh
    mode: 0644
  become: yes

- name: "Add Intellij to system applications"
  template:
    src: idea.desktop.j2
    dest: /usr/share/applications/idea.desktop
    mode: 0644
  become: yes
