---

- stat:
    path: "{{idea.dir}}"
  register: idea_dir

- name: Create {{ parent_dir }} directory
  file:
    path: "{{ parent_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: yes

- block:

  - name: Create {{ idea.dir }} directory
    file:
      path: "{{ idea.dir }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: directory

  - debug:
      msg: "download url : {{idea.url}}"

  - name: get Idea Intellij tarball
    get_url:
      url: "{{idea.url}}"
      dest: "/tmp/{{idea.file}}"

  - name: Unarchive Intellij
    shell: "tar xfz /tmp/{{idea.file}} --strip-components 1 -C {{idea.dir}}"

  - name: Remove old symlink
    file:
      path: "{{idea.parent_dir}}/idea"
      state: absent

  - file:
      src: "{{idea.dir }}"
      dest: "{{idea.parent_dir}}/idea"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: link

  when: idea_dir.stat.isdir is not defined

- name: Remove old path configuration
  file:
    path: /etc/profile.d/idea.sh
    state: absent
  become: yes

- name: "Configuring Idea Intellij {{idea.dir}} and add $PATH."
  template:
    src: idea.sh.j2
    dest: /etc/profile.d/idea.sh
    mode: 0644
  become: yes

- name: "Add Intellij to system applications"
  template:
    src: idea.desktop.j2
    dest: /usr/share/applications/idea.desktop
    mode: 0644
  become: yes
