---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Define common_packages.
  set_fact:
    common_packages: "{{ __common_packages | list }}"
  when: common_packages is undefined

# Setup/install tasks.
- include: setup-{{ ansible_distribution }}.yml
