---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Define common_packages.
  set_fact:
    common_packages: "{{ __common_packages | list }}"
  when: common_packages is undefined

# Setup/install tasks.
- include: setup-{{ ansible_distribution }}.yml


# - name: Ensure the system can use the HTTPS transport for APT
#   stat: path=/usr/lib/apt/methods/https
#   register: apt_https_transport

# - name: Install HTTPS transport for APT
#   yum: pkg=apt-transport-https state=installed
#   when: not apt_https_transport.stat.exists

#- name: Enable all repositories in sources.list
#  replace: dest=/etc/apt/sources.list regexp='^#\s?deb(.+)http://(.+)/ubuntu(.+)$' replace='deb\1http://\2/ubuntu\3' backup=yes

# - name: Ensure that repositories are up to date
#   yum: update_cache=yes cache_valid_time={{ aptcachetime }}


# Install
# - name: install common packages
#   yum: pkg={{ item }}
#        state=present
#   become: yes
#   with_items: "{{ common_packages }}"
#     - bash-completion
#     - build-essential
#     - bzip2
#     - colortest
#     - curl
#     - diffutils
#     - dnf
#     - dos2unix
#     - gawk
#     - gcc
#     - git
#     - grep
#     - gzip
#     - htop
#     - httping
#     - iftop
#     - iotop
#     - less
#     - make
#     - nano
#     - nfs-common
#     - nmap
#     - ntop
#     - openssl
#     - p7zip
#     - pbzip2
#     - pwgen
#     - rar
#     - software-properties-common
#     - tar
#     - unzip
#     - vim
#     - wget
#     - whois
#     - zip
#     - unzip
#
# - name: Upgrade installed packages
#   yum: upgrade=yes
