---

- name: check if Slack is installed?
  command: "apt list --installed | grep slack | grep {{ slack.version }}"
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no
#
# - debug:
#     msg: "current_version : {{ current_version.stdout }}"

- block:

  - name: Install slack for Debian OS family
    package:
      deb: "{{slack.url_deb}}"
    become: yes

  # when: current_version.stdout is defined and slack.version not in current_version.stdout
  when: current_version.stdout | version_compare(slack.version, '>')
