---

- name: "Create {{ parent_dir }} directory"
  file:
    path: "{{ parent_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: yes

- stat:
    path: "{{eclipse.dir}}"
  register: eclipse_dir


- block:

  - debug:
      msg: "download url : {{eclipse.url}}"

  - name: get Eclipse tarball
    get_url:
      url: "{{eclipse.url}}"
      dest: "/tmp/{{eclipse.file}}"

  - name: Unarchive Eclipse
    unarchive:
      src: "/tmp/{{eclipse.file}}"
      dest: "/tmp"
      copy: no

  - name: Create {{eclipse.dir}} directory
    command: "mv /tmp/eclipse {{eclipse.dir}}"

  - name: Remove old symlink
    file:
      path: "{{parent_dir}}/eclipse"
      state: absent

  - name: Create symlink
    file:
      src: "{{eclipse.dir}}"
      dest: "{{parent_dir}}/eclipse"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: link

  when: eclipse_dir.stat.isdir is not defined


- name: Remove old path configuration
  file:
    path: /etc/profile.d/eclipse.sh
    state: absent
  become: yes

- name: "Configuring Eclipse {{eclipse.dir}} and add $PATH."
  template:
    src: eclipse.sh.j2
    dest: /etc/profile.d/eclipse.sh
    mode: 0644
  become: yes

- name: "Add Eclipse to system applications"
  template:
    src: Eclipse.desktop.j2
    dest: /usr/share/applications/Eclipse.desktop
    mode: 0644
  become: yes

- name: "Add Eclipse logo to eclipse application"
  copy:
    src: eclipse.png
    dest: "{{eclipse.dir}}/eclipse.png"
    mode: 0644
  become: yes
