---

- name: Define apps_dir
  set_fact:
    apps_dir: "{{ apps_dir }}"
  when: apps_dir is undefined

- stat:
    path: "{{ apps_dir }}/eclipse"
  register: eclipse_dir

- name: "Create {{ apps_dir }} directory"
  file:
    path: "{{ apps_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: yes

- block:

  - debug:
      msg: "download url : {{eclipse.url}}"

  - name: get Eclipse tarball
    get_url:
      url: "{{eclipse.url}}"
      dest: "/tmp/eclipse-jee-{{eclipse.version}}-R-linux-gtk-x86_64.tar.gz"

  - name: Unarchive Eclipse
    unarchive:
      src: "/tmp/eclipse-jee-{{eclipse.version}}-R-linux-gtk-x86_64.tar.gz"
      dest: "{{ apps_dir }}"
      copy: no

  when: eclipse_dir.stat.isdir is not defined


- name: Remove old path configuration
  file:
    path: /etc/profile.d/eclipse.sh
    state: absent
  become: yes

- name: "Configuring Eclipse {{apps_dir}}/eclipse-{{eclipse.version}} and add $PATH."
  template:
    src: eclipse.sh.j2
    dest: /etc/profile.d/eclipse.sh
    mode: 0644
  become: yes

- name: "Add Eclipse to system applications"
  template:
    src: Eclipse.desktop.j2
    dest: /usr/share/applications/Eclipse.desktop
    mode: 0644
  become: yes

- name: "Add Eclipse logo to eclipse application"
  copy:
    src: eclipse.png
    dest: "{{ apps_dir }}/eclipse/eclipse.png"
    mode: 0644
  become: yes
