---


- stat:
    path: "{{ eclipse.home_parent_dir }}/eclipse"
  register: eclipse_dir

- name: "Create {{ eclipse.home_parent_dir }} directory"
  file:
    path: "{{ eclipse.home_parent_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: yes

- block:

  - debug:
      msg: "download url : https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/{{eclipse.version}}/R/eclipse-jee-{{eclipse.version}}-R-linux-gtk-x86_64.tar.gz&mirror_id=1"

  - name: get Eclipse tarball
    get_url:
      # url: "http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/neon/R/eclipse-jee-neon-R-linux-gtk-x86_64.tar.gz&mirror_id=96"
      # url: "https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/R/eclipse-jee-oxygen-R-linux-gtk-x86_64.tar.gz&r=1"
      url: "https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/{{eclipse.version}}/R/eclipse-jee-{{eclipse.version}}-R-linux-gtk-x86_64.tar.gz&mirror_id=1"
      dest: "/tmp/eclipse-jee-{{eclipse.version}}-R-linux-gtk-x86_64.tar.gz"

  - name: Unarchive Eclipse
    unarchive:
      src: "/tmp/eclipse-jee-{{eclipse.version}}-R-linux-gtk-x86_64.tar.gz"
      dest: "{{ eclipse.home_parent_dir }}"
      copy: no

  when: eclipse_dir.stat.isdir is not defined


- name: Remove old path configuration
  file:
    path: /etc/profile.d/eclipse.sh
    state: absent
  become: yes

- name: "Configuring Eclipse {{eclipse.home_parent_dir}}/eclipse-{{eclipse.version}} and add $PATH."
  template:
    src: eclipse.sh.j2
    dest: /etc/profile.d/eclipse.sh
    mode: 0644
  become: yes

- name: "Add Eclipse to system applications"
  template:
    src: Eclipse.desktop.j2
    dest: /usr/share/applications/Eclipse.desktop
    mode: 0644
  become: yes

- name: "Add Eclipse logo to eclipse application"
  copy:
    src: eclipse.png
    dest: "{{ eclipse.home_parent_dir }}/eclipse/eclipse.png"
    mode: 0644
  become: yes
