---

# - name: Ensure dependencies are installed.
#   package:
#     name: '{{ item }}'
#     state: present
#   become: yes
#   with_items:
#     - libvirt-devel
    # - vagrant-libvirt
    # - vagrant


- name: install the vagrant packages
  package: name={{ item }}
       state=present
  with_items:
    - https://releases.hashicorp.com/vagrant/{{vagrant.version}}/vagrant_{{vagrant.version}}_x86_64.rpm
  when: ansible_os_family == "RedHat"
  become: yes
