---

- name: check if Oracle JDK is installed?
  shell: java -version 2>&1 | grep -i 'Java(TM) SE Runtime Environment' | awk '{print $6}' | sed 's/)/ /'
  # shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: current_version
  changed_when: false
  # failed_when: false
  ignore_errors: true
  args:
    warn: no

- debug:
    msg: "Required version = {{ jdk.version }} and current_version = {{ current_version.stdout }}"

- block:
  - name: Ensure jdk dependencies are  installed.
    package:
      name: '{{ item }}'
      state: present
    become: yes
    with_items:
      - software-properties-common
      - python-software-properties
      - debconf-utils

  - name: Import WebUpd8 PGP key
    apt_key: keyserver=keyserver.ubuntu.com id=0xEEA14886 state=present
    become: yes

  - name: add repository for Oracke jdk 8
    apt_repository: repo=ppa:webupd8team/java state=present
    become: yes

  # - name: set licence selected
  #   shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  #   become: yes
  #
  # - name: set licence seen
  #   shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
  #   become: yes

  - name: Accept Java 8 License
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
    become: yes

  - name: Install Oracle Jkd 8
    apt: name={{item}} state=latest
    with_items:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
    become: yes

  - name: Set this as default Java; also environment variables
    apt: pkg="oracle-java8-set-default" state=present force=yes

  - name: Remove old path configuration
    file:
      path: /etc/profile.d/jdk.sh
      state: absent
    become: yes

  - name: "Configuring JAVA_HOME and add $PATH."
    template:
      src: jdk.sh.j2
      dest: /etc/profile.d/jdk.sh
      mode: 0644
    become: yes
    
  when: current_version.stdout is defined and jdk.version not in current_version.stdout
  # when: current_version.stdout | version_compare(jdk.version, '>')
