---

# - name: Import Datastax RPM key
#   rpm_key:
#     key: https://www.apache.org/dist/cassandra/KEYS
#     state: present
#   become: yes

- name: Adding Datastax repository
  template:
    src: cassandra.repo.j2
    dest: /etc/yum.repos.d/cassandra.repo
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install Cassandra.
  package: name=cassandra state=present
  become: yes
