---

- name: check if Sqlectron is installed?
  command: "apt list --installed | grep -i sqlectron | grep {{ sqlectron.version }}"
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- debug:
    msg: "current_version : {{ current_version.stdout }}"

- block:

  - name: install the Sqlectron packages
    package:
      deb: "{{ sqlectron.url_deb}}"
    become: yes

  when: current_version.stdout | version_compare(sqlectron.version, '>')
