---

- name: check if Sqlectron is installed?
  command: "apt list --installed | grep -i sqlectron | grep {{ sqlectron.version }}"
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- debug:
    msg: "current_version : {{ current_version.stdout }}"

- block:

  - name: Download sqlectron for Debian OS family
    get_url: url={{ sqlectron.url_deb }} dest={{sqlectron.file_deb}}

  - name: Install sqlectron for Debian OS family
    apt: deb={{sqlectron.file_deb}}
    become: yes

  when: current_version.stdout | version_compare(sqlectron.version, '>')
