---

- name: check if NPM is installed?
  shell: npm -v 2>&1
  register: npm_current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- block:
  - name: Define npm user
    set_fact:
      npm.user: "{{ ansible_user }}"
    when: npm.user is not defined

  - debug:
      msg: "Installing global npm packges with user {{ npm.user }}"

  - name: Create npm global directory
    file:
      path: "{{ npm.config_prefix }}"
      owner: "{{ npm.user }}"
      group: "{{ npm.user }}"
      state: directory

  - name: "Configuring npm global packages directory per user {{ npm.config_prefix }} and add to global $PATH."
    template:
      src: npm.sh.j2
      dest: /etc/profile.d/npm.sh
      mode: 0644
    become: yes

  - name: Ensure npm global packages are installed.
    npm:
      name: "{{ item.name | default(item) }}"
      version: "{{ item.version | default('latest') }}"
      global: yes
      state: latest
    environment:
      NPM_CONFIG_PREFIX: "{{ npm.config_prefix }}"
      NODE_PATH: "{{ npm.config_prefix }}/lib/node_modules"
    with_items: "{{ npm.global_packages }}"
    ignore_errors: yes

  - name: Install packages from package.json.
    npm:
      path: "{{ npm.package_json_path }}"
    when: npm.package_json_path is defined and npm.package_json_path

  when: npm_current_version.stdout | version_compare(npm.version, '>')
