---

- name: check if Atom is installed?
  command: "apt list --installed | grep atom | grep {{ atom.version }}"
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- block:

  - name: Install atom for Debian OS family
    apt:
      deb: "{{atom.url_deb}}"
    become: yes

  when: current_version.stdout | version_compare(atom.version, '>')
