---

- name: check if Atom is installed?
  command: "apt list --installed | grep atom | grep {{ atom.version }}"
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- block:
  - name: Download atom for Debian OS family
    get_url: url={{ atom.url_deb }} dest={{atom.file_deb}}

  - name: Install atom for Debian OS family
    apt: deb={{atom.file_deb}}
    become: yes

  # when: current_version.stdout is defined and atom.version not in current_version.stdout
  when: current_version.stdout | version_compare(atom.version, '>')
