---

- name: check if Atom is installed?
  command: "dnf list installed | grep atom | grep {{ atom.version }}"
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- debug:
    msg: "current_version : {{ current_version.stdout }}"

- block:

  - name : unistall older version
    package:
      name: atom
      state: absent

  - name: install the atom packages
    package:
      name: {{ item }}
      state: present
    with_items:
      - "{{ atom.url_rpm}}"
    become: yes

  when: current_version.stdout | version_compare(atom.version, '>')
