---

- name: check if Atom is installed?
  command: "dnf list installed | grep atom | grep {{ atom.version }}"
  register: current_version
  changed_when: false
  ignore_errors: true
  args:
    warn: no

- debug:
    msg: "current_version : {{ current_version.stdout }}"

- name: install the atom packages
  yum: name={{ item }}
       state=present
  with_items:
    - "{{ atom.url_rpm}}"
  when: current_version.stdout is defined and atom.version not in current_version.stdout
  become: yes
