---

- stat:
    path: "{{ maven.home_parent_dir }}/apache-maven-{{ maven.version }}"
  register: maven_dir

- debug:
    msg: "maven_dir = {{ maven_dir.stat.isdir }}"
  when: maven_dir.stat.isdir is defined

- name: "Create {{ maven.home_parent_dir }} directory"
  file:
    path: "{{ maven.home_parent_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: yes

- block:

  - name: get Maven tarball
    get_url:
      url: "https://www.apache.org/dist/maven/maven-{{ maven.major }}/{{ maven.version }}/binaries/apache-maven-{{ maven.version }}-bin.tar.gz"
      dest:    "/tmp/apache-maven-{{ maven.version }}-bin.tar.gz"

  - name: Unarchive maven
    unarchive:
      src: "/tmp/apache-maven-{{ maven.version }}-bin.tar.gz"
      dest: "{{maven.home_parent_dir}}"
      copy: no

  when: maven_dir.stat.isdir is not defined


- name: Remove old symlink
  file:
    path: "{{maven.home_parent_dir}}/maven"
    state: absent

- file:
    src: "{{maven.home_parent_dir}}/apache-maven-{{ maven.version }}"
    dest: "{{maven.home_parent_dir}}/maven"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link

- name: Remove old path configuration
  file:
    path: /etc/profile.d/maven.sh
    state: absent
  become: yes

- name: "Configuring maven home {{maven.home_parent_dir}}/apache-maven-{{maven.version}} and add $PATH."
  template:
    src: maven.sh.j2
    dest: /etc/profile.d/maven.sh
    mode: 0644
  become: yes

# - name: Maven path configuration
#   lineinfile:
#     dest: /etc/profile.d/maven.sh
#     line: "{{ item.line }}"
#     create: yes
#     state: present
#   with_items:
#     - { line: 'M2_HOME={{maven.home_parent_dir}}/apache-maven-{{maven.version}}' }
#     - { line: 'PATH=$PATH:$M2_HOME/bin' }
