---

- name: Ensure old versions of Docker along with its dependencies are not installed.
  package:
    name: '{{ item }}'
    state: absent
  become: yes
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  become: yes

- name: Add Docker repository.
  get_url:
    url: "https://download.docker.com/linux/fedora/docker-ce.repo"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install Docker.
  package: name=docker state=present
  become: yes
