---
- hosts: localhost
  connection: local

  vars_files:
    - vars/default-config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ['always']

  roles:
    - role: common
    - role: motd
    - role: sudoers
    - role: rpmfusion
    - role: docker
    - role: nodejs
    - role: jdk
    - role: maven
    - role: sublime
    - role: atom
    - role: cassandra
    - role: slack
    - role: chrome
    - role: sqlectron
    - role: tomcat
    - role: eclipse
    - role: idea
    - role: bash-customization
    # - role: virtualbox
    # - role: vagrant
    # - role: mailhog

  tasks:
    # - include: tasks/ansible-setup.yml
    # - include: tasks/gem-packages.yml
    # - include: tasks/npm-packages.yml
    # - include: tasks/ppip-ackages.yml
    - include: tasks/cleanup.yml

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
