---


- name: Ensure dependencies are installed.
  package:
    name: '{{ item }}'
    state: absent
  become: yes
  with_items:
    - kernel-devel

- name: Add VirtualBox repository.
  get_url:
    url: "{{rpm_repo_url}}"
    dest: '/etc/yum.repos.d/virtualbox.repo'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Ensure VirtualBox is installed.
  package:
    name: VirtualBox-{{virtualbox.version}}
    state: present
    enablerepo: 'virtualbox'
  become: yes
