---

- name: Ensure pre-requisite packages are installed.
  package:
    name: '{{ item }}'
    state: present
  become: yes
  with_items:
    - gcc
    - dkms
    - make
    - qt
    - libgomp
    - patch
    - kernel-headers
    - kernel-devel
    - binutils
    - glibc-headers
    - glibc-devel
    - "http://rpmfind.net/linux/centos/7.5.1804/os/x86_64/Packages/fontforge-20120731b-12.el7.x86_64.rpm"

- name: Add VirtualBox repository.
  get_url:
    url: "http://download.virtualbox.org/virtualbox/rpm/rhel/virtualbox.repo"
    dest: '/etc/yum.repos.d/virtualbox.repo'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Ensure VirtualBox is installed.
  package:
    name: VirtualBox-{{virtualbox.version}}
    state: present
    enablerepo: 'virtualbox'
    disable_gpg_check: true
  become: yes
