---
- name: Import Sublime RPM key
  rpm_key:
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    state: present
  become: yes

- name: Add Sublime repository.
  get_url:
    url: "{{rpm_repo_url}}"
    dest: '/etc/yum.repos.d/sublime.repo'
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Ensure Sublime is installed.
  package:
    name: sublime-text
    state: present
    enablerepo: 'sublimetext'
  become: yes
